### ISSUE TITLE
Scoping docsify styles

### ISSUE THREAD

**Issue by MohammadYounes** [QingWei-Li/docsify#131]
Hi

I wanted to use docsify to document a css framework, which includes actual samples. But docsify styles are element based - specially those under `markdown-section` - which cascades over the actual samples producing undesirable results.

Looking at the code, I found that you've [re-implemented](https://github.com/QingWei-Li/docsify/blob/master/src/core/render/compiler.js#L54) the marked renderer and I was wondering if it's possible to scope the styles for both docsify/marked generated html. 

For example:
```js
return `<h${level} data-scope="docsify"  ...> ... </h${level}>`
```

Thanks!

**Comment by QingWei-Li** [comment]
@MohammadYounes Hi,

Most of the markdown styles I know are element based. And the users can re-implemented the renderer in docsify, we can't make sure that the users are also set scoped attribute.

Maybe we can providing special attribute (sush as `<div data-custom></div>`) to prevent the use of default style.

For example.

```css
.markdown-section :not([data-custom]) h1 {
 /* */
}
.markdown-section :not([data-custom]) p {
 /* */
}
```

```html
<main class="markdown-section">
<h1> docsify css </h1>

<h1 data-custom> no style </h1>

<div data-custom>
  <h1>Haha</h1>
  <p>Haha</p>
</div>
</main>
```

What do you think?

**Comment by MohammadYounes** [comment]
@QingWei-Li 

Usually I won't face such a problem in case I was documenting an API or a JS library, But for a CSS framework this won't work, as the presented actual samples will be inside `.markdown-section`.

What broke first was the heading samples and I managed to get around it by making the following update to `vue.css` theme.

```css
.markdown-section h1[id], .markdown-section h2[id], .markdown-section h3[id], .markdown-section h4[id], .markdown-section strong {
  color: #2c3e50;
  font-weight: 600;
}
```

The above works great, because the rendered markdown headers all have an ID. But what about other tags, such as `table`, `th`, `td`, `p`, `ul`, `ol` ... etc.

I ended up cloning the repo and modifying the renderer to include `data-docsify` along with each rendered markdown element and then limiting `vue.css` theme to that scope:

```css
.markdown-section ul[data-docsify], .markdown-section ol[data-docsify] {
  padding-left: 1.5em;
}
```

What do you think about this ? Can such scoping be incorporated into docsify ?
