### ISSUE TITLE
suggestion: remove all css nowrap

### ISSUE THREAD

**Issue by willin** [QingWei-Li/docsify#228]
such as: 

<img width="1345" alt="wx20170805-093840 2x" src="https://user-images.githubusercontent.com/1890238/28991890-f10f5322-7954-11e7-9203-422f2b946644.png">

```css
.markdown-section code {
    border-radius: 2px;
    color: #e96900;
    font-size: 12.8px;
    font-size: .8rem;
    margin: 0 2px;
    padding: 3px 5px;
    white-space: nowrap;
}
```

the best practice is 'pre-wrap', @QingWei-Li
