### ISSUE TITLE
Styling <kbd> element

### ISSUE THREAD

**Issue by liulex** [QingWei-Li/docsify#37]
I currently style `<kbd>` by my custom css:

```css
kbd {
    display: inline-block;
    padding: 3px 5px;
    margin-bottom : 3px;
    font-size: 12px !important;
    line-height: 12px;
    vertical-align: middle;
    border: solid 1px #ccc;
    border-radius: 3px;
}
```
Result:
![snipaste20161221_175812](https://cloud.githubusercontent.com/assets/2010459/21384889/4ea77f38-c7a7-11e6-9a4c-b8169996b59c.jpg)

But since keys are common to see in a documentation, it would be better to support it by default.
