### ISSUE TITLE
Adding logo on the sidenav

### ISSUE THREAD

**Issue by AfricanProgrammer** [QingWei-Li/docsify#466]
Hi.I am trying to add a logo on top of the sidenav.I am unable to do so.I am using the dark theme.
![capture](https://user-images.githubusercontent.com/8723783/38940529-9bad2a94-432a-11e8-80ed-f256e54c12ad.PNG).Please note the image above was added using chrome inspect 
Kindly advice.

**Comment by dmed256** [comment]
@AfricanProgrammer Here's an example for swapping the order 

http://libocca.org/#/guide/user-guide/introduction

The CSS used to swap them:

```css
.search {
    position: absolute;
    width: 100%;
    top: 70px;
    border-top: 1px solid #EEEEEE;
    z-index: 10;
    background-color: #FFFFFF;
}

.sidebar > h1 {
    position: absolute;
    top: 20px;
    left: 0;
    width: 100%;
}

.sidebar-nav {
    position: absolute;
    width: 100%;
    top: 130px;
}
```
