### ISSUE TITLE
how to hide the sidebar on small screen

### ISSUE THREAD

**Issue by Xcorpio** [QingWei-Li/docsify#487]
Hi, i want to hide the sidebar.
 below is what i do?
```html
  <style>
    aside {
      display: none;
    }
    .sidebar-toggle {
      display: none;
    }
  </style>
</head>
<body class="close">
```
it works ok on big screen?

on a little screen

<img width="855" alt="2018-05-16 8 15 21" src="https://user-images.githubusercontent.com/4575409/40116332-edaeeba8-5945-11e8-88dd-883dfccf7497.png">

look the picture above,  there is some space on the left.

Can we hava a option to specify if there sidebar should be renderred?

**Comment by Xcorpio** [comment]
the white space is not sidebar

**Comment by SidVal** [comment]
@Xcorpio can you share with us your repo's URL ?

**Comment by Xcorpio** [comment]
http://ojlm.tech
https://github.com/ojlm/ojlm
https://github.com/ojlm/ojlm/blob/master/docs/index.html
@SidVal

**Comment by dmed256** [comment]
I found the CSS to hide and show the sidebar to be backwards for desktop and mobile
I couldn't find a good solution to keep the sidebar closed and open it with JS

`index.html`
```html
  <body class="no-sidebar">
```

CSS
```css
body.no-sidebar .sidebar,
body.no-sidebar .sidebar-toggle {
    display: none !important;
}

body.no-sidebar .content {
    left: 0px !important;
}
```

JS
```js
// As a docsify plugin
  hook.doneEach(() => {
    const file = vm.route.file;
    if (!file.match(/^[^/]*\.md$/)) {
      dom.classList.remove('no-sidebar');
    } else {
      dom.classList.add('no-sidebar');
    }
  });
```

I only wanted the sidebar for routes in a directory
- No sidebar: https://libocca.org/#/gallery
- Sidebar: https://libocca.org/#/guide/user-guide/introduction

**Comment by Xcorpio** [comment]
thanks, `no-sidebar` works.

**Comment by tkkcc** [comment]
@dmed256's answer is awesome. If only to hide sidebar in homepage, just css is enough.
```css
body[data-page="main.md"] .sidebar,
body[data-page="main.md"] .sidebar-toggle {
  display: none !important;
}
body[data-page="main.md"] .content {
  left: 0px !important;
}
```
