### ISSUE TITLE
Multi-language navbars

### ISSUE THREAD

**Issue by liulex** [QingWei-Li/docsify#6]
The top navbar and the newly supported sidebar seem to be static only, which is bad if we have pages for different languages while the titles of the navbar items can only have one language.

As to the top navbar, being static is fine if we arrange the items like "En, 中文".
However, if we arrange them like "Download, Language (En, 中文)", where the items in parentheses  mean they are contained in a dropdown list. When we switched to the Chinese page, the English navbar will be undesirable.

Maybe we can offer a way to bind each page with its navbars?

For example, we have four navbars: nav-top-1, nav-top-2, nav-left-1, nav-left-2.
If a page does not explicitly specify its navbars, the defualt ones  will be used for it. If a page says it wants nav-top-2 and nav-left-2, these two will be used.

But how do we bind a page with a navbar? Sorry I have little knowledge about css or javascript...

Another possible improvement may be to allow the user to write their custom sidebars using markdown, just like Github Wiki does. They put it in _Sidebar.md.

Sorry if I am asking for too much. :sweat_smile:

**Comment by QingWei-Li** [comment]
Maybe we can copy GitBook directory structure, such as

```text
-| zh-cn\
-| en\
  -| article1.md
  -| article2.md
  -| README.md
  -| _sidebar.md
  -| _navbar.md
-| README.md
-| 404.html
```

The `README.md` in the root can be used as gitbook `LANG.md` what to choose language. Or can be used as the default language directory, such as

```text
-| zh-cn\
    -| article1.md
    -| article2.md
    -| _sidebar.md
    -| _navbar.md
    -| README.md
-| article1.md
-| article2.md
-| _sidebar.md
-| _navbar.md
-| README.md
-| 404.html
```

What do you think? I can work it tonight.

**Comment by liulex** [comment]
I would prefer the latter one, so that there would be no 'en' in the urls of English pages.
Your solution is great. Thanks!

**Comment by QingWei-Li** [comment]
Both will be implemented. 😄

**Comment by liulex** [comment]
Even better 👍

**Comment by QingWei-Li** [comment]
Custom sidebars is be implemented in `0.5.0`, You can refer to https://docsify.js.org/zh-cn#sidebar

**Comment by liulex** [comment]
Excellent! I've tried it out, everything works well, except one thing missing...

`_navbar.md` doesn't support sub-level, i.e. lines like these cannot be parsed as a dropdown list:
```
- [Dowload](https://example.com/)
- [Language](/)
  - [English](/)
  - [中文](/zh-cn)
```

I know it can be achieved via css (you told me :smile: ), and I made it. However, this way I can only have one navbar, which means the English and Chinese pages cannot have different navbars.

Therefore, maybe it's better to support dropdown list natively?

**Comment by QingWei-Li** [comment]
I have no idea about dropdown list, but I'll try it tonight.

We can have different navbars, such as

```markdown
-| zh-cn\
    -| article1.md
    -| article2.md
    -| _sidebar.md
    -| _navbar.md
    -| README.md
-| article1.md
-| article2.md
-| _sidebar.md
-| _navbar.md
-| README.md
-| 404.html
```

**Comment by liulex** [comment]
Yes I know that. Only when we write it in .md, but that way I lost my dropdown list. For dropdown list, I need to write it in 404.html, then I lost different navbars... :joy:

**Comment by QingWei-Li** [comment]
Ok, i see. How do you achieve the dropdown list , you can show me the code for reference? thanks~

**Comment by liulex** [comment]
Sure.

In 404.html:
```html
  <nav>
    <div class="nav-dropdown-container">
    	<a>Language</a>
    	<div class="nav-dropdown">
      		<a href="/">En</a>
      		<a href="/zh-cn">中文</a>
    	</div>
  </div>
  </nav>
```

Custom css:
```css
nav .nav-dropdown {
    display: none;
    position: absolute;
    top: 100%;
    left: 0;
    background-color: #fff;
    padding: 10px 0;
    border: 1px solid #ddd;
    border-bottom-color: #ccc;
    text-align: left;
    border-radius: 4px;
    white-space: nowrap;
}

.nav-dropdown-container:hover .nav-dropdown {
        display: block;
}

.nav-dropdown-container {
    position: relative;
    display: inline-block;
}

.nav-dropdown-container a {
    display: block;
}

.nav-dropdown-container a.active {
    border-bottom: none;
}
```
