### ISSUE TITLE
能不能添加nav固定的功能

### ISSUE THREAD

**Issue by LancelotLewis** [QingWei-Li/docsify#70]
如题

**Comment by QingWei-Li** [comment]
自己写样式咯，一行样式搞定 😂
```css
nav {
  display: fixed;
}
```
